language: generic
services:
  - docker

before_install:
  - docker build -t ahmedbahy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ahmedbahy/docker-react npm run test -- --coverage